RegisterCommand(Config.command, function(source, args, rawCommand)
    local src = source
	local reporter = GetPlayerName(source)
    local msg = rawCommand:sub(4)
    if  args[1] ~= nil then
        local report = {
            {
                ["type"] = "rich",
                ["title"] = Config.title,
                ["color"] = Config.color,
                ["description"] = msg,
                ["footer"] = {
                    ["text"] = "Generated By: "..reporter.. "."
                }
            }
        }
        PerformHttpRequest(Config.webHookURL, function(err, text, headers) end, 'POST', json.encode({embeds = report}), { ['Content-Type'] = 'application/json' })
        TriggerClientEvent('chatMessage', src,  Config.successchat)
    else 
        TriggerClientEvent('chatMessage', src,  Config.errorchat)
    end
end, false)